version: '3'

services:
  testing:
    container_name: testing
    image: lmab-tests
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "composer install && composer update --prefer-source && composer test"
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    logging:
      driver: none